// Package verify turns evidence into a calibrated probability that a
// predicate holds, and a tier saying how much that probability can be trusted.
//
// The organising principle is provenance first, detection second. A photo with
// no capture binding is compatible with the right scene today, the same scene
// last year, a different address, a photo of a printout, or something a model
// generated. No amount of pixel forensics closes that gap, and betting the
// product on winning a detection arms race would be a mistake. So the strong
// signals here are the ones an honest provider can produce cheaply and a
// dishonest one cannot fake: a per-job challenge nonce written into the shot,
// a capture that came through our own page, and the absence of that image
// anywhere else in the corpus.
package verify

import (
	"fmt"
	"math"
	"sort"
	"strings"
)

// Tier is how much a verdict's confidence can be trusted, given what the
// evidence structurally permits.
type Tier string

const (
	TierV0 Tier = "V0" // a signed claim, no artifact
	TierV1 Tier = "V1" // an artifact with deterministic checks
	TierV2 Tier = "V2" // artifact + challenge nonce + adjudication
	TierV3 Tier = "V3" // two independent sources that agree
)

// Rank orders the tiers so a requested tier can be compared against what the
// evidence actually supported.
func (t Tier) Rank() int {
	switch t {
	case TierV3:
		return 3
	case TierV2:
		return 2
	case TierV1:
		return 1
	default:
		return 0
	}
}

// AtLeast reports whether t meets or exceeds want.
func (t Tier) AtLeast(want Tier) bool { return t.Rank() >= want.Rank() }

// Ceiling is the highest probability a tier may report. These are deliberately
// hard caps applied after aggregation: a model that is certain cannot lift a
// verdict past what the evidence structurally supports.
// CaptureAttested reports whether an artifact carries proof that a camera —
// not a person with a file picker — produced these pixels.
//
// Nothing does today. There is no C2PA parsing and no hardware attestation, so
// this is a constant, and the honest thing is to leave it visible in the code
// rather than hidden behind a flag that is never set.
//
// Note what it is not: a device key proves a browser signed the upload, which
// says nothing about where the bytes came from. Somebody can generate an image
// and sign that upload perfectly.
const CaptureAttested = false

func (t Tier) Ceiling(hasProvenance bool) float64 {
	// Without capture attestation, every tier collapses to the same ceiling.
	//
	// The tiers above V1 were written for a world where a photograph is at
	// worst a photograph of the wrong thing. Generated imagery breaks the
	// premise: a challenge code can be composited into a synthetic scene, and
	// two "independent" sources can both be generated by one person, so
	// corroboration stops meaning independence. Reporting 0.995 for that would
	// be selling a number we cannot stand behind, and the whole product is the
	// claim that our numbers mean something.
	//
	// Restore the ladder when capture is attested in hardware, not before.
	if !CaptureAttested {
		if hasProvenance {
			return 0.85
		}
		return 0.72
	}
	switch t {
	case TierV3:
		return 0.995
	case TierV2:
		return 0.965
	case TierV1:
		if hasProvenance {
			return 0.90
		}
		// The honest number for an unbound photo. It is not a claim about this
		// image; it is a claim about the population of submissions, which is
		// exactly what an adversary paid on the verdict will attack.
		return 0.72
	default:
		return 0.80
	}
}

// IndepClass groups signals that are not independent evidence of each other.
// Everything derived from "was this captured by a real device just now" moves
// together, so stacking those signals would triple-count one question.
type IndepClass string

const (
	ClassCapture       IndepClass = "capture_device"
	ClassNovelty       IndepClass = "novelty"
	ClassProvenance    IndepClass = "provenance"
	ClassContent       IndepClass = "content"
	ClassIntegrity     IndepClass = "integrity"
	ClassCorroboration IndepClass = "corroboration"
)

// Signal is one piece of evidence about the predicate, expressed as a
// log-likelihood ratio in nats. Positive favours the predicate holding.
type Signal struct {
	Verifier string     `json:"verifier"`
	Feature  string     `json:"feature"`
	Value    string     `json:"value"`
	LLR      float64    `json:"llr"`
	Class    IndepClass `json:"class"`
	// Fatal signals are policy, not probability: they reject the submission
	// outright regardless of what the arithmetic says. Keeping the two
	// separate means the probability stays honest for calibration even when
	// the decision is categorical.
	Fatal  bool           `json:"fatal,omitempty"`
	Detail map[string]any `json:"detail,omitempty"`
	Cents  int            `json:"cents,omitempty"`
}

// Decision is what the exchange does with the aggregate.
type Decision string

const (
	DecisionAccept   Decision = "accept"
	DecisionReject   Decision = "reject"
	DecisionEscalate Decision = "escalate"
)

// Result is the aggregated judgment.
type Result struct {
	PTrue    float64  `json:"p_true"`
	Tier     Tier     `json:"tier"`
	Required Tier     `json:"required_tier"`
	Decision Decision `json:"decision"`
	// Admissible means the evidence is good enough to be paid the base fee:
	// it reached the requested tier and tripped no fatal signal.
	Admissible bool `json:"admissible"`
	// MetTier separates "the evidence was too weak for what was asked" from
	// "the evidence was fraudulent", which are different provider failures and
	// should not be conflated in the reliability record.
	MetTier    bool     `json:"met_tier"`
	Signals    []Signal `json:"signals"`
	PriorLogit float64  `json:"prior_logit"`
	// ProvenanceLogit is how strongly the authenticity signals argue that this
	// artifact is what it claims to be. It never moves PTrue.
	ProvenanceLogit float64 `json:"provenance_logit"`
	Cents           int     `json:"cents"`
	// AggregateHash commits to the signals and parameters that produced PTrue,
	// so a confidence number is reproducible rather than asserted.
	AggregateHash string `json:"aggregate_hash"`
	Fatal         string `json:"fatal,omitempty"`
}

// Aggregation parameters. Exposed because they are part of what the
// AggregateHash commits to; changing them changes verdicts, so they are
// versioned data rather than constants buried in code.
type Params struct {
	// Lambda discounts each additional signal within one independence class.
	Lambda float64
	// ClassCap bounds how far any single class may move the odds, in nats.
	ClassCap float64
	// LLRClamp bounds any one signal. 3 nats is about 20:1 — no single check
	// may be more than twenty times more likely under one hypothesis.
	LLRClamp float64
	// PriorClamp keeps reputation from ever becoming a verdict on its own.
	PriorMin, PriorMax float64
}

func DefaultParams() Params {
	return Params{
		Lambda: 0.35, ClassCap: 2.5, LLRClamp: 3.0,
		PriorMin: 0.02, PriorMax: 0.95,
	}
}

// answers separates the two questions a signal can speak to. Conflating them
// is a subtle and expensive mistake: provenance signals say whether an artifact
// is authentic and fresh, not whether the claim it is offered for is true. If
// they are summed into one probability, a perfectly authenticated photograph of
// an empty wall starts certifying that a sign is present, because the nonce
// matched and the capture was recent.
func (c IndepClass) answersPredicate() bool {
	switch c {
	case ClassContent, ClassCorroboration:
		return true
	}
	return false
}

// Aggregate combines signals with a provider's prior into a probability.
//
// Signals within an independence class are discounted rather than multiplied:
// the strongest counts fully, the rest at lambda. Then each class is capped.
// Naive multiplication across correlated signals is how verification systems
// talk themselves into 0.9999 on a single photograph.
//
// The two questions are kept apart. PTrue answers "does the predicate hold",
// and only content and corroboration move it. Admissibility answers "is this
// evidence worth anything", and that is where provenance, freshness, novelty
// and integrity land.
func Aggregate(prior float64, signals []Signal, tier, required Tier, hasProvenance bool, p Params) Result {
	prior = clamp(prior, p.PriorMin, p.PriorMax)
	logit := math.Log(prior / (1 - prior))
	res := Result{PriorLogit: logit, Tier: tier, Required: required, Signals: signals}

	byClass := map[IndepClass][]float64{}
	for _, s := range signals {
		res.Cents += s.Cents
		if s.Fatal {
			res.Fatal = s.Feature + "=" + s.Value
		}
		llr := clamp(s.LLR, -p.LLRClamp, p.LLRClamp)
		byClass[s.Class] = append(byClass[s.Class], llr)
	}

	classes := make([]IndepClass, 0, len(byClass))
	for c := range byClass {
		classes = append(classes, c)
	}
	sort.Slice(classes, func(i, j int) bool { return classes[i] < classes[j] })

	for _, c := range classes {
		v := byClass[c]
		// Strongest first, by magnitude.
		sort.Slice(v, func(i, j int) bool { return math.Abs(v[i]) > math.Abs(v[j]) })
		sum := v[0]
		for _, extra := range v[1:] {
			sum += p.Lambda * extra
		}
		sum = clamp(sum, -p.ClassCap, p.ClassCap)
		if c.answersPredicate() {
			logit += sum
		} else {
			res.ProvenanceLogit += sum
		}
	}

	pt := 1 / (1 + math.Exp(-logit))
	pt = math.Min(pt, tier.Ceiling(hasProvenance))
	res.PTrue = clamp(pt, 0.01, 0.995)

	// Admissibility is judged against the tier the buyer paid for, not against
	// whatever the evidence happened to support. A provider who submits an
	// unbound photo for a job that required a bound one has not done the work,
	// so it does not earn the base fee — otherwise "submit anything" is a
	// profitable strategy.
	res.MetTier = tier.AtLeast(required)
	// Provenance has to be net-positive for the artifact to count as evidence
	// at all. A submission whose authenticity signals argue against it is not
	// admissible however confident the content read was.
	provenanceOK := res.ProvenanceLogit > 0
	switch {
	case res.Fatal != "":
		res.Decision, res.Admissible = DecisionReject, false
	case !res.MetTier || !provenanceOK:
		res.Decision, res.Admissible = DecisionReject, false
	case res.PTrue >= 0.35 && res.PTrue <= 0.65:
		res.Decision, res.Admissible = DecisionEscalate, true
	default:
		res.Decision, res.Admissible = DecisionAccept, true
	}
	res.AggregateHash = hashAggregate(prior, signals, tier, p)
	return res
}

// Satisfied reports whether the aggregate clears the buyer's requested
// confidence. Kept separate from Admissible so that an honest "the sign is not
// there" is still paid the base fee: the provider did the work, the answer was
// simply no.
func (r Result) Satisfied(requiredBP int64) bool {
	return r.Admissible && r.Decision == DecisionAccept && r.PTrue*10000 >= float64(requiredBP)
}

// Explain renders why the exchange reached its conclusion, in the terms a
// buyer cares about. It distinguishes "we certified this is false" from "we
// could not certify either way", which are very different products.
func (r Result) Explain(requiredBP int64) string {
	switch {
	case r.Fatal != "":
		return "rejected: " + r.Fatal
	case !r.MetTier:
		return fmt.Sprintf("could not certify: evidence reached %s, the job required %s", r.Tier, r.Required)
	case r.ProvenanceLogit <= 0:
		return "rejected: the evidence's own authenticity signals do not support it"
	case r.Decision == DecisionEscalate:
		return "inconclusive: needs human review"
	case r.PTrue*10000 >= float64(requiredBP):
		return fmt.Sprintf("certified true at %.1f%%", r.PTrue*100)
	default:
		return fmt.Sprintf("not certified: %.1f%% is below the %.0f%% asked for", r.PTrue*100, float64(requiredBP)/100)
	}
}

// ConfidenceBP renders the probability in basis points for the verdict entry,
// which carries no floats.
func (r Result) ConfidenceBP() int64 { return int64(math.Round(r.PTrue * 10000)) }

func clamp(v, lo, hi float64) float64 { return math.Max(lo, math.Min(hi, v)) }

func hashAggregate(prior float64, signals []Signal, tier Tier, p Params) string {
	var b strings.Builder
	fmt.Fprintf(&b, "v1|prior=%.6f|tier=%s|lambda=%.3f|cap=%.3f|clamp=%.3f",
		prior, tier, p.Lambda, p.ClassCap, p.LLRClamp)
	ordered := append([]Signal(nil), signals...)
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].Feature != ordered[j].Feature {
			return ordered[i].Feature < ordered[j].Feature
		}
		return ordered[i].Value < ordered[j].Value
	})
	for _, s := range ordered {
		fmt.Fprintf(&b, "|%s=%s:%.4f", s.Feature, s.Value, s.LLR)
	}
	return sha256Hex([]byte(b.String()))
}

// MaxAchievableBP is the highest confidence a tier can deliver, in basis
// points, given a perfectly clean submission. The exchange checks a requested
// confidence against this before quoting: selling 99% on evidence that
// structurally tops out at 96.5% would be selling something that cannot be
// delivered, which is the one failure that would destroy the product's reason
// to exist.
func MaxAchievableBP(t Tier, hasProvenance bool) int64 {
	return int64(t.Ceiling(hasProvenance) * 10000)
}

// ErrUnachievable reports that no evidence at this tier could satisfy the
// requested confidence.
type ErrUnachievable struct {
	Requested, Achievable int64
	Tier                  Tier
}

func (e ErrUnachievable) Error() string {
	return fmt.Sprintf(
		"tier %s tops out at %.1f%% confidence, but %.1f%% was asked for; buy a higher tier or ask for less",
		e.Tier, float64(e.Achievable)/100, float64(e.Requested)/100)
}

// CheckAchievable returns an error if the requested confidence cannot be met at
// this tier even by flawless evidence.
func CheckAchievable(t Tier, requestedBP int64) error {
	// A single-source tier is also bounded by how far one content signal can
	// move the odds from a neutral prior, which is well below the structural
	// ceiling. Corroboration is what buys the top of the range.
	achievable := MaxAchievableBP(t, true)
	if t.Rank() < TierV3.Rank() {
		if single := int64(8100); achievable > single {
			achievable = single
		}
	}
	if requestedBP > achievable {
		return ErrUnachievable{Requested: requestedBP, Achievable: achievable, Tier: t}
	}
	return nil
}
