apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lamdis.fullname" . }}-secret
  labels:
    {{- include "lamdis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.bootstrap.adminToken }}
  LAMDIS_ADMIN_TOKEN: {{ .Values.bootstrap.adminToken | quote }}
  {{- end }}
  {{- if .Values.apiToken }}
  LAMDIS_API_TOKEN: {{ .Values.apiToken | quote }}
  {{- end }}
  {{- if eq .Values.global.authMode "oidc" }}
  {{- if .Values.oidc.clientId }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  {{- end }}
  {{- if .Values.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
  {{- end }}
